name: Stat Scrape for Data

on:
  push:
    branches:
      - main

jobs:
  scrape-county-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fatch-depth: 0
    - name: Script
      run: ./scraper.ps1
      shell: pwsh