name: Stat Scrape for Data

on:
  push:
    branches:
      - main

jobs:
  scrape-county-data:
    runs-on: ubuntu-latest
    steps:
      - name: Script
        run: |
          $uri = "https://vt.ncsbe.gov/RegStat/Results/?date=05%2F21%2F2022"
          $html = Invoke-WebRequest -Uri $uri
          $data -match "var data = (.*?)]"
          $jsonData = $Matches[0] -replace "var data = ", ''
          $countyData = ConvertFrom-Json $jsonData
          $unionCountryData = $countyData | Where-Object {$_.CountyName -eq "UNION"}
          echo $unionCountryData
        shell: powershell